[package]
name = "oauth-diagnostic-tool"
version = "0.0.5"
description = "Tool for going through the auth server and client side of OAuth flows"
authors = ["Sam Sovereign"]
license = "Apache 2.0"
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.6", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.10.3", features = ["devtools"] }
tauri-plugin-log = "2"
rusqlite = { version = "0.31", features = ["bundled"] }
rand = "0.8"
axum = "0.7"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v4"] }
base64 = "0.22"
form_urlencoded = "1.2"
reqwest = { version = "0.12", features = ["json"] }
sha2 = "0.10"
jsonwebtoken = "9"
chrono = { version = "0.4", features = ["serde"] }
tauri-plugin-updater = "2.10.1"
tauri-plugin-process = "2"
